### ISSUE TITLE
Feature request: rafflez 4 xenoes

### ISSUE THREAD

**Issue by UnicornOnLSD** [CM-14/CM-14#2362] opened 2024-06-09 21:18 UTC
## Description

After going on da xeno side during the first playtest, any and all xeno spawn were given to whoever could spam the mouse harder on were the request button could be.
Adding raffles would allow to watch the game better, and you know, they just exist so might as well slap them, maybe a raffle of 5 second should be enough

**Comment by Tunguso4ka** [comment] 2024-06-10 06:45
I cast the DUPLICATE OF #2383

**Comment by Tunguso4ka** [comment] 2024-06-10 06:46
oh it was first. Ooops.

**Closed** 2024-06-11 22:26 UTC
Labels: Issue: Feature Request
