### ISSUE TITLE
Can't hit weeds underneath puddles

### ISSUE THREAD

**Issue by K-Dynamic** [CM-14/CM-14#2392] opened 2024-06-10 06:18 UTC
## Description
Puddles block weeds, can't whack them

**Reproduction**
1. Bleed over weed
2. Knife weed under puddle
3. No weed deweeding

**Screenshots**
no

**Additional context**
explosives probably work because they don't rely on melee being blocked by puddles

**Comment by Tunguso4ka** [comment] 2024-06-10 06:26
Duplicate of #2369

**Closed by Tunguso4ka** 2024-06-10 06:26 UTC
Labels: duplicate
